name: GeoNetwork Metadata Signoff Checklist
description: This checklist is to be completed for each metadata record in the MAPS catalogue before it is published.
title: "[Dataset]: "
labels: ["documentation"]
assignees:
  - dzvoti
body:
  - type: markdown
    attributes:
      value: |
        Thank you using this repository to review MAPS GeoNetwork metadata records. Please loginto [MAPS GeoNetwork](https://metadata.micronutrient.support/geonetwork/srv/eng/catalog.signin?redirect=https%3A%2F%2Fmetadata.micronutrient.support%2Fgeonetwork%2Fsrv%2Feng%2Fcatalog.search%3Bjsessionid%3DFCF5548CA8501232E70F21B437D881AD%23%2Fhome) to review your assigned record.
        
        ---
        
        Please use the priority levels below as guidance in this signoff process.
        
        |Priority Level| Description|
        |-|-|
        |***|Mandatory, do not publish/sign-off without it|
        |**|High, the resource can be published but seek further information from MAPS contact person after signoff and update the record|
        |*|Low, the resource can be published without this detail|      
  - type: input
    id: identifier
    attributes:
      label: Metadata identifier ***
      description: Priority *** - This hash key is automatically generated by GeoNetwork, please copy and paste it below.
      placeholder: e.g., 0f3ee4b5-d765-4cba-b6f3-d1092941f4e5
    validations:
      required: true
  - type: input
    id: metadata_link
    attributes:
      label: MAPS netadata link
      description: Please paste the link for the record you are reviewing here
      placeholder: eg. https://metadata.micronutrient.support/geonetwork/srv/eng/catalog.search#/metadata/0f3ee4b5-d765-4cba-b6f3-d1092941f4e5      
  - type: dropdown
    id: resource_name
    attributes:
      label: Resource Name ***
      description: Priority *** - Check if the name corresponds with the resource
      options:
        - Sufficient
        - Not sufficient
    validations:
      required: true      
  - type: dropdown
    id: abstract
    attributes:
      label: Abstract ***
      description: Priority *** - Data summary and processing methodology can also be captured here.e.g., The data used to compile the tables were gathered from scientific literature on Malawian food analyses.
      options:
        - Sufficient
        - Not sufficient
    validations:
      required: true      
  - type: dropdown
    id: status
    attributes:
      label: Status
      description: Priority *** - Verify status e.g., Completed/Incomplete/Ongoing
      options:
        - Sufficient
        - Not sufficient
    validations:
      required: true
  - type: dropdown
    id: temporal_extent
    attributes:
      label: Temporal Extent ***
      description: Priority *** - Verify temporal extent e.g. January 2019 – March 2021
      options:
        - Sufficient
        - Not sufficient
    validations:
      required: true
  - type: dropdown
    id: spatial_extent
    attributes:
      label: Spatial Extent ***
      description: Priority *** - Verify spatial extent i.e. Which Area/Country/Region does the data resource cover? e.g., Malawi/SADC/Africa
      options:
        - Sufficient
        - Not sufficient
    validations:
      required: true
  - type: dropdown
    id: date_published
    attributes:
      label: Date Published **
      description: Priority ** - The date when the resource was published by the e.g. July 2021
      options:
        - Sufficient
        - Not sufficient
    validations:
      required: true
  - type: dropdown
    id: categories
    attributes:
      label: Categories **
      description: Priority ** - Verify proper metadata category assignment e.g. Boundaries/Health
      options:
        - Sufficient
        - Not sufficient
    validations:
      required: true
  - type: dropdown
    id: other_keywords
    attributes:
      label: Other keywords ***
      description: Priority *** - Any other key worlds that the data resource can be associated with. e.g., Micronutrient, Ethiopia. Note that at least 3 key words should be present to allow easy indexing and searches
      options:
        - Sufficient
        - Not sufficient
    validations:
      required: true
  - type: dropdown
    id: language
    attributes:
      label: Language *
      description: Priority * - Is the metadata resource language captured?
      options:
        - Sufficient
        - Not sufficient
    validations:
      required: true
  - type: dropdown
    id: legal_constraints
    attributes:
      label: Legal constraints ***
      description: Priority *** - Verify the licence with data origin e.g. Full access conditions are available [here](https://ephi.gov.et/images/nutrition/ethiopian-national-vitamin-a-deficiency-survey)
      options:
        - Sufficient
        - Not sufficient
    validations:
      required: true
  - type: dropdown
    id: resource_contact
    attributes:
      label: Contact for the resource ***
      description: Priority *** - Verify the contacts i.e. Who is the originator/responsible party for the data? e.g., Organisation-**Ethiopian Public Health Institute (EPHI)**, Principal investigator-**Mr Dilnesaw Zerfu**, email- **zerfu@ephi.et**
      options:
        - Sufficient
        - Not sufficient
    validations:
      required: true
  - type: dropdown
    id: update_frequency
    attributes:
      label: Update frequency **
      description: Priority ** - Verify i.e. How frequent is the resource collected? e.g., As needed/quarterly/bi-annually
      options:
        - Sufficient
        - Not sufficient
    validations:
      required: true
  - type: dropdown
    id: representation_type
    attributes:
      label: Representation type *
      description: Priority * - Verify e.g., Vector or Raster
      options:
        - Sufficient
        - Not sufficient
    validations:
      required: true
  - type: dropdown
    id: coordinate_reference_system
    attributes:
      label: Coordinate reference system *
      description: Priority * - Verify e.g., WGS 1984
      options:
        - Sufficient
        - Not sufficient
    validations:
      required: true
  - type: dropdown
    id: maps_contact
    attributes:
      label: MAPS Contact ***
      description: Priority *** - Check if MAPS contact details are recorded e.g. Binyam Girma
      options:
        - Sufficient
        - Not sufficient
    validations:
      required: true
  - type: dropdown
    id: resource_download_link
    attributes:
      label: Resource download links **
      description: Priority ** - Only to be included if the licence permits it. Verify that the resource links are not broken.
      options:
        - Sufficient
        - Not sufficient
    validations:
      required: true
  - type: dropdown
    id: publish_permission
    attributes:
      label: Published/Did not Publish
      description: Have you published/signed-off the metadata record in its current state?
      options:
        - "Yes"
        - "No (comment below)"
    validations:
      required: true
  - type: textarea
    id: additional_comments
    attributes:
      label: Additional comments
      description: Do you have any additional comments for the MAPS Geonetwork administrator
      render: shell      
